root    = "."
tmp_dir = "tmp"

[build]
bin         = " " # skip
full_bin    = " " # skip
log         = "air_ts.log"
cmd         = "tools/run build ts"
include_dir = [ "web/typescript" ]
include_ext = [ "ts" ]

[log]
time = true
