root    = "."
tmp_dir = "tmp"

[build]
bin         = " "
full_bin    = " "
cmd         = "sassc web/scss/main.scss web/static/css/main.css"
log         = "air_scss.log"
include_dir = [ "web/scss" ]
include_ext = [ "scss" ]
